//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados_cursos
    {
        public int IdEmpleado { get; set; }
        public int IdCurso { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
