//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Empleados_cursos = new HashSet<Empleados_cursos>();
        }
    
        public int id { get; set; }
        [System.ComponentModel.DisplayName("Nombre")]
        public string NombreEmpleado { get; set; }
        [System.ComponentModel.DisplayName("Porcentaje Adicional")]
        public Nullable<int> PorcAdicional { get; set; }
        [System.ComponentModel.DisplayName("Pago por punto")]
        public Nullable<int> PagoPorPunto { get; set; }
        [System.ComponentModel.DisplayName("Puesto")]
        public int IdPuesto { get; set; }
        [System.ComponentModel.DisplayName("Departamento")]
        public int IdDepartamento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Puesto Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_cursos> Empleados_cursos { get; set; }
    }
}
